// Send remote keys to the YouTube TV target. Usage: node tools/ytdrive.mjs "down,right,enter" [perKeyMs]
import { Client } from 'ssh2'; import { readFileSync } from 'fs'; import http from 'http'; import net from 'net'; import { WebSocket } from 'ws';
const KEYS=(process.argv[2]||'').split(',').map(s=>s.trim()).filter(Boolean);
const PER=parseInt(process.argv[3])||600;
const KM={up:{k:'ArrowUp',c:'ArrowUp',v:38},down:{k:'ArrowDown',c:'ArrowDown',v:40},left:{k:'ArrowLeft',c:'ArrowLeft',v:37},right:{k:'ArrowRight',c:'ArrowRight',v:39},enter:{k:'Enter',c:'Enter',v:13},ok:{k:'Enter',c:'Enter',v:13},back:{k:'Backspace',c:'Backspace',v:8}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const c=new Client(); c.on('ready',()=>{const srv=net.createServer(s=>c.forwardOut('127.0.0.1',0,'127.0.0.1',9998,(e,rs)=>{if(e){s.end();return;}s.pipe(rs).pipe(s);}));srv.listen(0,'127.0.0.1',()=>{const port=srv.address().port;http.get('http://127.0.0.1:'+port+'/json',r=>{let d='';r.on('data',x=>d+=x);r.on('end',async()=>{const app=JSON.parse(d).find(p=>p.title&&p.title.toLowerCase().includes('youtube'));if(!app){console.log('no youtube');process.exit(1);}const ws=new WebSocket(app.webSocketDebuggerUrl.replace(/127\.0\.0\.1:\d+/,'127.0.0.1:'+port));let id=1;const call=(m,p)=>new Promise(res=>{const i=id++;ws.send(JSON.stringify({id:i,method:m,params:p||{}}));const h=x=>{const mm=JSON.parse(x);if(mm.id===i){ws.off('message',h);res(mm.result);}};ws.on('message',h);});await new Promise(r=>ws.on('open',r));
for(const k of KEYS){const m=KM[k];if(!m){console.log('?key',k);continue;}await call('Input.dispatchKeyEvent',{type:'keyDown',key:m.k,code:m.c,windowsVirtualKeyCode:m.v,nativeVirtualKeyCode:m.v});await call('Input.dispatchKeyEvent',{type:'keyUp',key:m.k,code:m.c,windowsVirtualKeyCode:m.v,nativeVirtualKeyCode:m.v});await sleep(PER);}
console.log('sent:',KEYS.join(','));ws.close();srv.close();c.end();process.exit(0);});}).on('error',e=>{console.log('err',e.message);process.exit(1);});});});
c.connect({host:'192.168.50.94',port:9922,username:'prisoner',privateKey:readFileSync(process.env.HOME+'/.ssh/tv_webos'),passphrase:'4E7082',algorithms:{serverHostKey:['ssh-rsa']}});
